version: "3.7"
services:
  website:
    image: blkskr/bookstore-api
    restart: always
    depends_on: 
      - database
    ports:
      - "80:80"
    networks:
      - whitenet
  database:
    image: mysql:5.7 
    environment:
      MYSQL_ROOT_PASSWORD: blkskr
      MYSQL_USER: blkskr
      MYSQL_PASSWORD: blkskr.me
      MYSQL_DATABASE: bookstore_db
    networks:
      - whitenet
networks:
  whitenet:
    driver: bridge
