version: "3.7"
services:
  website:
    image: bb4it/bookstore-api
    restart: always
    depends_on: 
      - database
    ports:
      -80:80
    networks:
      - whitenet
  database:
    image: mysql:5.7 
    environment:
      MYSQL_ROOT_PASSWORD: Bbeyaz
      MYSQL_USER: bb4it
      MYSQL_PASSWORD: bb4it.me
      MYSQL_DATABASE: bookstore_db
    networks:
      - whitenet
networks:
  whitenet:
    driver: bridge
